//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Default target language 的本地化字符串。
        /// </summary>
        internal static string DefaultTargetLanguage {
            get {
                return ResourceManager.GetString("DefaultTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default translation target language, default is &quot;Auto&quot;. 的本地化字符串。
        /// </summary>
        internal static string DefaultTargetLanguageDescription {
            get {
                return ResourceManager.GetString("DefaultTargetLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic reading result 的本地化字符串。
        /// </summary>
        internal static string EnableAutoRead {
            get {
                return ResourceManager.GetString("EnableAutoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show jump to dictionary button 的本地化字符串。
        /// </summary>
        internal static string EnableJumpDictionary {
            get {
                return ResourceManager.GetString("EnableJumpDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add a button to quick jump to dictionary, default is youdao. 的本地化字符串。
        /// </summary>
        internal static string EnableJumpDictionaryDescription {
            get {
                return ResourceManager.GetString("EnableJumpDictionaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable search suggest 的本地化字符串。
        /// </summary>
        internal static string EnableSuggest {
            get {
                return ResourceManager.GetString("EnableSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please try later 的本地化字符串。
        /// </summary>
        internal static string Error_Init_SubTitle {
            get {
                return ResourceManager.GetString("Error_Init_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing apis... 的本地化字符串。
        /// </summary>
        internal static string Error_Init_Title {
            get {
                return ResourceManager.GetString("Error_Init_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The URL has been copied. go to your browser and visit the website for help. 的本地化字符串。
        /// </summary>
        internal static string Error_Null_ModalSubTitle {
            get {
                return ResourceManager.GetString("Error_Null_ModalSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied! 的本地化字符串。
        /// </summary>
        internal static string Error_Null_ModalTitle {
            get {
                return ResourceManager.GetString("Error_Null_ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press [Enter] to get a link to GitHub Issues for help 的本地化字符串。
        /// </summary>
        internal static string Error_Null_SubTitile {
            get {
                return ResourceManager.GetString("Error_Null_SubTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result is null, some error happen in translate. Check out your network! 的本地化字符串。
        /// </summary>
        internal static string Error_Null_title {
            get {
                return ResourceManager.GetString("Error_Null_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some errors occurred while searching for suggestions. 的本地化字符串。
        /// </summary>
        internal static string Error_Suggest_Title {
            get {
                return ResourceManager.GetString("Error_Suggest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize translation components 的本地化字符串。
        /// </summary>
        internal static string InitSubTitle {
            get {
                return ResourceManager.GetString("InitSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing... 的本地化字符串。
        /// </summary>
        internal static string InitTitle {
            get {
                return ResourceManager.GetString("InitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic 的本地化字符串。
        /// </summary>
        internal static string Lan_ar {
            get {
                return ResourceManager.GetString("Lan_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string Lan_auto {
            get {
                return ResourceManager.GetString("Lan_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string Lan_de {
            get {
                return ResourceManager.GetString("Lan_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Lan_en {
            get {
                return ResourceManager.GetString("Lan_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spanish 的本地化字符串。
        /// </summary>
        internal static string Lan_es {
            get {
                return ResourceManager.GetString("Lan_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string Lan_fr {
            get {
                return ResourceManager.GetString("Lan_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew 的本地化字符串。
        /// </summary>
        internal static string Lan_he {
            get {
                return ResourceManager.GetString("Lan_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        internal static string Lan_it {
            get {
                return ResourceManager.GetString("Lan_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string Lan_ja {
            get {
                return ResourceManager.GetString("Lan_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean 的本地化字符串。
        /// </summary>
        internal static string Lan_ko {
            get {
                return ResourceManager.GetString("Lan_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        internal static string Lan_ru {
            get {
                return ResourceManager.GetString("Lan_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese (Simplified) 的本地化字符串。
        /// </summary>
        internal static string Lan_zh_CHS {
            get {
                return ResourceManager.GetString("Lan_zh-CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese (Traditional) 的本地化字符串。
        /// </summary>
        internal static string Lan_zh_CHT {
            get {
                return ResourceManager.GetString("Lan_zh-CHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy (Enter), Subtitle[Shift+Enter] 的本地化字符串。
        /// </summary>
        internal static string Menu_Copy_Title {
            get {
                return ResourceManager.GetString("Menu_Copy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read [Ctrl+Enter] 的本地化字符串。
        /// </summary>
        internal static string Menu_Read_Title {
            get {
                return ResourceManager.GetString("Menu_Read_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A simple translation plugin, based on Youdao Translation 的本地化字符串。
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translator 的本地化字符串。
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active second target lanuage, will display after main target. 的本地化字符串。
        /// </summary>
        internal static string SecondTargetLanguageDescription {
            get {
                return ResourceManager.GetString("SecondTargetLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second target lanuage 的本地化字符串。
        /// </summary>
        internal static string SecondTargetLanuage {
            get {
                return ResourceManager.GetString("SecondTargetLanuage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display original query 的本地化字符串。
        /// </summary>
        internal static string ShowOriginalQuery {
            get {
                return ResourceManager.GetString("ShowOriginalQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add a item at the end of the results with &quot;[query raw]&quot;. 的本地化字符串。
        /// </summary>
        internal static string ShowOriginalQueryDescription {
            get {
                return ResourceManager.GetString("ShowOriginalQueryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to dictionary 的本地化字符串。
        /// </summary>
        internal static string Tag_GoToDictionary_Title {
            get {
                return ResourceManager.GetString("Tag_GoToDictionary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [query raw] 的本地化字符串。
        /// </summary>
        internal static string Tag_QueryRaw {
            get {
                return ResourceManager.GetString("Tag_QueryRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [second lanuage] 的本地化字符串。
        /// </summary>
        internal static string Tag_SecondLanguage {
            get {
                return ResourceManager.GetString("Tag_SecondLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use system default proxy 的本地化字符串。
        /// </summary>
        internal static string UseSystemProxy {
            get {
                return ResourceManager.GetString("UseSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a proxy at request time, default to true. 的本地化字符串。
        /// </summary>
        internal static string UseSystemProxyDescription {
            get {
                return ResourceManager.GetString("UseSystemProxyDescription", resourceCulture);
            }
        }
    }
}
